config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'my_products', to: 'products#my_products'

  resources :products

  resources :products do
    resources :cart_products, only: [:create]
    resources :orders, only: [:new, :create]
  end

  resources :cart_products, only: [:destroy]
  resources :carts, only: [:show]
  resources :orders, only: [:index, :show, :destroy]

  root to: 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_products
  has_many :products, through: :cart_products
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :user

  validates :quantity, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :cart_products
  has_many :orders
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :carts
  has_many :products, dependent: :destroy
  has_many :orders
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :address, :name, :category, :email, presence: true
  validates :name, :address, length: { minimum: 8 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :category, :address, :email, :password, :photo)}
    # devise_parameter_sanitizer.permit(:sign_up, keys: [:photo])
    # devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :category, :address, :email, :password, :photo)}
  end
end

app/controllers/cart_products_controller.rb
class CartProductsController < ApplicationController

  def create
    @product = Product.find(params[:product_id])
    @cart_product = CartProduct.new(cart_product_params)
    @cart_product.product = @cart_product
    @cart_product.save
    # if @cart_product.save
    #     redirect_to products_path(@product)
    # else
    #     render 'products/show'
    # end
  end

  def show
    @order = Order.find(params[:id])
  end

  def destroy
    @cart_product = CartProduct.find(params[:id])
    @cart_product.destroy
    redirect_to cart_path(@cart_product.product)
  end

  #Não criamos a rota show do carrinho. Imaginamos que o path seria /carts/:id

  private

  def cart_product_params
    params.require(:cart_product).permit(:quantity, :cart_id, :products_id)
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = Cart.find(params[:id])
    @user = current_user
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @user = current_user
    @orders = @user.orders
  end

  def create
    @product = Product.find(params[:product_id])
    @user = current_user
    @order = Order.new(strong_params)
    @order.product = @product
    @order.user = @user
    if @order.save
      redirect_to orders_path
    else
      render 'products/show'
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to orders_path
  end

  private

  def strong_params
    params.require(:order).permit(:quantity)

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:search].present?
      @products = Product.where('name ILIKE ?', "%#{params[:search]}%")
    else
      @products = Product.all
    end
    @user = current_user
    return unless @user&.geocoded?

    @distances = {}
    @products.each do |product|
      next unless product.user&.geocoded?

      producer = product.user
      @distances[producer.id] = num_formated(producer.distance_to(@user.address), 1)
    end
  end

  def my_products
    @user = current_user
    @id = current_user.id
    @products = Product.where(user_id: @id)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    if @product.save
      redirect_to product_path(@product)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if @product.user != current_user
      redirect_to root_path, alert: 'Not authorized'
      # return
    else
      @product.destroy
      redirect_to products_path, notice: 'Product was successfully destroyed.'
    end
  end

  def show
    @user = current_user
    @product = Product.find(params[:id])
    @markers = [@user, @product.user].map do |user|
      next unless user&.geocoded?

      { lat: user.latitude, lng: user.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { user: user }) }
    end
    @order = Order.new
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def set_restaurant
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :price.to_s, :quantity, :search, :photo, :unit_measurement)
  end

  def num_formated(num, precision)
    num_rounded = num.round(precision)
    int_txt = num_rounded.to_i.to_s.reverse.gsub(/...(?=.)/, '\&.').reverse
    frac_txt = precision.positive? ? ",#{num_rounded.to_s[-1 - (precision - 1)]}" : ""
    "#{int_txt}#{frac_txt}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def price_mask_real(price)
    number_to_currency(price, unit: 'R$', separator: ',', delimiter: '.')
  end
end

app/views/carts/show.html.erb
<div class="container">
  <h1><%= @user.email %> Cart</h1>
  <table class="table table-borered">
    <tbody>
      <thead>
        <th>Item</th>
        <th>Quantity</th>
        <th>Price</th>
        <th>Action</th>
      </thead>
      <% @cart.cart_products.each do |cart_product| %>
        <tr>
          <td><%= cart_product.product.name %></td> <!-- # To improve -->
          <td><%= cart_product.quantity %></td>
          <td><%= cart_product.price %></td>
          <td>
            <%= link_to cart_product_path(cart_product), method: :delete, data: { confirm: 'Are you sure?' } do %>
              <i class="fa fa-trash destroy_cart_product"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Organics</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>  <!-- IMPORTANTE!!! esta linha não constou nos slides -->
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<div class="container mt-5">

 <h2>Meus Pedido</h2>
  <table class="table table-center mt-3">
    <tbody>
      <thead>
        <th>Item</th>
        <th>Descrição</th>
        <th>Quantidade</th>
        <th>Preço</th>
        <th>Unidade de medida</th>
        <th>Total</th>
      </thead>
      <% total = 0 %>
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.product.name %></td> <!-- # To improve -->
          <td><%= order.product.description %></td>
          <td class="table-number"><%= order.quantity %></td>
          <td class="table-number"><%= order.product.price %></td>
          <td><%= order.product.unit_measurement %></td>

          <td class="table-number">R$ <%= (sprintf "%.2f", order.product.price * order.quantity).to_s.gsub('.', ',') %> </td>
          <% total += order.product.price * order.quantity %>
          <td>
            <%= link_to order_path(order), method: :delete, data: { confirm: 'Are you sure?' } do %>
              <i class="fa fa-trash destroy_cart_product"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
     <tfoot>
    <tr>
      <th id="total" colspan="5"></th>
      <td> R$ <%= (sprintf "%.2f", total).to_s.gsub('.', ',') %> </td>
    </tr>
   </tfoot>
  </table>
  <%= link_to 'Continuar comprando', products_path, class: "btn btn-warning" %>
  <%= link_to 'Comprar', products_path, data: { confirm: 'Obrigada! Em até duas horas o vendedor encaminhará um email com a confirmação da compra e orientação de' }, class: "btn btn-warning" %>
</div>

app/views/orders/show.html.erb
<h1>Order</h1>
<p> <%= @order.product.name %> </p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/products/_cindex.html.erb
<div class="banner" style="background-image: url('<%= image_path 'organic.jpg' %>')">
  <div class="banner-content">
    <h1>Fresh Organic Market</h1>
    <%# <p>Produtos orgânicos fresquinhos</p> %>
    <p>
      <span id="banner-typed-text"></span>
    </p>
  </div>
</div>

<div class="container">
<div class="search text-center">
  <%= form_tag products_path, :method => "get" do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag("Buscar Produto", :name => nil, class: "btn btn-warning") %>
  <% end %>
</div>
<br>

<div class="container">
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-12 col-md-6 col-lg-3">
        <div class="card-product">
          <%= link_to "", product_path(product), class: 'card-link' %>
          <% img = product.photo.attached? ? product.photo.key : "" %>
          <%= cl_image_tag img, height: 300, width: 400, crop: :fill %>
          <div class="card-product-infos">
            <div>
              <% dist_txt = @distances&.key?(product.user.id) ? " a #{@distances[product.user.id]}km" : '' %>
              <h2><%= "#{product.name}#{dist_txt}" %></h2>
              <p><%= product.description.split('').first(20).join.strip + "..." %></p>
            </div>
            <h2 id="card-product-pricing"><small><%= price_mask_real(product.price) %>/<%= product.unit_measurement %> </small> </h2>
            <!--  <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />-->
          </div>
        </div>
      </div>
    <% end %>
   </div>
 </div>

app/views/products/_form.html.erb
<% btn_name = locals[:btn_name] %>
<%= simple_form_for @product do |f| %>

  <%= f.input :name, label: 'Produto', placeholder: 'Banana Nanica' %>
  <%= f.input :description, label: 'Descrição', placeholder: 'Possui casca fina de cor amarelo-esverdeada, polpa doce e macia e aroma agradável. Na média 1kg de banana contém de 10 a 12 unidades da fruta.' %>
  <%= f.input :price, label: 'Preço', placeholder: '6.90' %>
  <%#= f.input :quantity, label: 'Quantidade disponível', placeholder: '3' %>
  <%= f.input :unit_measurement, label: 'Unidade de medida', placeholder: 'Kg' %>
  <%= f.input :photo, as: :file, label: 'Foto do produto' %>
  <%= f.button :submit, "#{btn_name}", class: 'btn btn-warning' %>
<% end %>

app/views/products/_info_window.html.erb
<h2><%= user.name %></h2>
<p><%= user.address %></p>

app/views/products/edit.html.erb
<div class="container mt-5">
  <div class="edit-page">
    <h1>Altere seu produto</h1>
  </div>
  <%= render 'form', product: @product, locals: { btn_name: 'Editar Produto' }  %>
  <br>
  <div class="row justify-content-left">
    <div class="col-md-8">
    <%= link_to 'Voltar', products_path, class: "btn btn-warning" %>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<%= render 'cindex', product: @product %>

app/views/products/my_products.html.erb
<%= render 'cindex', product: @product %>

app/views/products/new.html.erb
<div class="container mt-5">
  <div class="edit-page">
    <h1>Cadastre seu Produto</h1>
  </div>
  <%= render 'form', product: @product, locals: { btn_name: 'Cadastrar Produto' }  %>
  <br>
  <div class="row justify-content-left">
    <div class="col-md-8">
    <%= link_to 'Voltar', products_path, class: "btn btn-warning" %>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="container mt-5">
  <div class="row mt-2">
    <div class="col">
      <p id="notice"><%= notice %></p>

      <hr>

      <p>
        <strong>Nome do Produtor:</strong>
        <%= @product.user.name %>
      </p>
      <p>
        <strong>Endereço:</strong>
        <%= @product.user.address %>
      </p>

      <hr>

      <p>
        <strong>Produto:</strong>
        <%= @product.name %>
      </p>
      <p>
        <strong>Descrição:</strong>
        <%= @product.description %>
      </p>
      <p>

        <strong>Preço:</strong>
        <%#= "#{(sprintf "%.2f", @product.price).to_s.gsub('.', ',')} #{@product.unit_measurement}" %>
        <%= "#{price_mask_real(@product.price)}/#{@product.unit_measurement}" %>
      </p>

        <% if @product.user != current_user%>
          <%= simple_form_for @order, url: product_orders_path(@product), method: :post do |f| %>

          <%= f.input :quantity, label: "Quantidade desejada em #{@product.unit_measurement}" %>

          <%= link_to 'Voltar', products_path, class: "btn btn-warning" %>
          <%= f.submit 'Adicionar ao carrinho', class: "btn btn-warning" %>
          <% end %>

        <% else %>

        <%= link_to 'Voltar', products_path, class: "btn btn-warning" %>
        <%= link_to 'Editar', edit_product_path(@product), class: "btn btn-warning" %>
        <%= link_to 'Excluir', product_path(@product), method: :delete, data: { confirm: 'Tem certeza que deseja excluir esse produto?' }, class: "btn btn-warning" %>

        <% end %>

    </div>

    <div class="col mt-3">
      <% img = @product.photo.attached? ? @product.photo.key : "" %>
      <%= cl_image_tag img, class: "rounded", height: 300, width: 400, crop: :fill %>
    </div>
  </div>
  <br>
  <div id="map"
  <div id="map mt-4"
     style="width: 80%;margin: 0 auto; height: 500px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to products_path, class: "navbar-brand" do %>
    <%= image_tag "logo3.png" %>
    <% end %>
    <%= link_to "Home", products_path, class: "navbar-nav mr-auto home"%>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Meus pedidos", orders_path, class: "nav-link" %>

        </li>
        <% if current_user.category == "Produtor(a)" %>
        <li class="nav-item active">
          <%= link_to "Meus produtos", my_products_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Novo Produto", new_product_path, class: "nav-link" %>
        </li>
        <% else %>

        <!-- <li class="nav-item active">
          <%#= link_to "Meu carrinho", orders_path, class: "nav-link" %>
        </li> -->

        <% end %>
        <li class="nav-link">
          <strong> <%= current_user.name %> </strong>
        </li>
        <li class="nav-item dropdown">
          <% img = current_user.photo.attached? ? current_user.photo.key : "avatar.jpg" %>
          <%= cl_image_tag img, class: "avatar dropdown-toggle", id: "navbarDropdown",
              data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Meu perfil", edit_user_registration_path, class: "dropdown-item" %>
          <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
       <% else %>
        <li class="nav-item">
          <%= link_to "Entrar", new_user_session_path, class: "nav-link btn btn-warning text-white" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<div class="fake-navbar">
</div>